config/routes.rb
Rails.application.routes.draw do

  # Comments routes.
  get 'uncomment', to: 'comments#destroy'
  
  # Likes routes.
  get 'like', to: "likes#create"
  get 'dislike', to: "likes#destroy"

  # Connections routes.
  resources :connections
  get 'add/friend', to: "connections#create"
  get 'remove/friend', to: "connections#destroy"

  # Search routes.
  get 'result', to: 'searches#result'
  get 'search', to: 'searches#search_user'

  # Post routes.
  resources :posts do
    resources :comments, except: [:index]
  end

  # Profile routes.
  resources :profiles, except: [:index, :destroy]

  # Devise users routes.
  devise_for :users

  # Pages controller. 
  root 'pages#home'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :location, presence: true
  validates :genre, presence: true
  validates :telephone, presence: true
  validates :date_birth, presence: true
  validates :occupation, presence: true

  def self.look_up(user_search)
    where("first_name like ?", "%#{user_search}%")
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :require_user
  before_action :user_has_profile, only: [:new, :create]
  before_action :same_user_and_profile, only: [:edit, :update, :destroy]

  # GET /profiles/1 or /profiles/1.json
  def show
    @user_posts = @profile.user.posts.order('created_at DESC')
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :location, :genre, :telephone, :date_birth, :occupation, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="relative z-0 mb-6 w-full group">
    <%= form.text_field :first_name, class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " " %>
    <%= form.label :first_name, style: "display: block", class:"absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %><br>
  </div>

  <div class="relative z-0 mb-6 w-full group">
    <%= form.text_field :last_name, class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " " %>
    <%= form.label :last_name, style: "display: block", class:"absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %><br>
  </div>

  <div class="relative z-0 mb-6 w-full group">
    <%= form.text_field :telephone, class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " " %>
    <%= form.label :telephone, style: "display: block", class:"absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %><br>
  </div>

  <div class="relative z-0 mb-6 w-full group">
    <%= form.text_field :occupation, class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " " %>
    <%= form.label :occupation, style: "display: block", class:"absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %><br>
  </div>

  <div class="mb-3 w-full">
    <%= form.label "Genre", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= form.radio_button :genre, "Male" %>
    <%= form.label :genre, "Male" %> |
    <%= form.radio_button :genre, "Female" %>
    <%= form.label :genre, "Female" %>
  </div>
  <br>

  <div class="mb-3 w-full">
    <%= form.label 'Profile photo', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= form.file_field :avatar, class:"block w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 cursor-pointer dark:text-gray-400 focus:outline-none focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
  </div>
  
  <br>
  <div class="mb-3 w-full">
    <%= form.label :location, style: "display: block", class:"mb-3" %>
    <%= form.select :location, ["Mexico", "United States", "Brazil", "Argentina", "Chile", "Canada", "Spain", "England", "France"], class: "bg-gray-200 w-full" %>
  </div>

  <div class="mb-3 w-full">
    <%= form.label :date_birth, style: "display: block", class:"mb-3" %>
    <%= form.date_field :date_birth %>
  </div>

  <br>
  <div class="text-center">
    <%= form.submit class: "inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out" %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <div class="flex flex-col items-center w-full bg-cyan-50 rounded-lg border shadow-md">
    <br>
    <div>
      <%= image_tag(profile.avatar, width: 200, class:"rounded-full") if profile.avatar.attached? %>
      <% if !profile.avatar.attached? %>
        <img src="<%= asset_path( 'image-blank.png' ) %>" width= "200px" class="rounded-full" />
      <% end %>
    </div>
    <div class="flex flex-col">
      <div class="flex flex-col justify-between p-4 leading-normal">
        <h3 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          <p class= "text-center">
            <%= profile.first_name %> <%= profile.last_name %> 
          </p>
        </h3>
        <h4>
          <p class="text-sm text-center font-bold">
            <%= profile.occupation %>
          </p>
        </h4>
        <div class="mt-2 text-center">
          <p>
            <span class="bg-green-100 text-gray-900 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded">
            <svg class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path></svg>
            <b>Joined: <%= time_ago_in_words(profile.user.created_at) %>.</b>
            </span>
          </p>
          <div class="mt-2 mb-3">
            <span class="bg-blue-100 text-blue-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">
              <svg class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path></svg>
              Friends: <%= profile.user.connections.count %>
            </span>
          </div>
          <div class="mt-5 mb-5">
            <span class="text-sm">
              <% if current_user != profile.user %>
                <% if Connection.look_connection(current_user.id, profile.user.id) %>
                  <%= link_to "Remove friend", remove_friend_path(user: current_user.id, friend: profile.user.id), class:"text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
                <% else %>
                  <%= link_to "Add friend", add_friend_path(user: current_user.id, friend: profile.user.id), class:"text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-green-300 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
                <% end %>
              <% end %>
            </span>
          </div>
          <p class="mb-3 text-sm">
            <strong>Location:</strong>
            <%= profile.location %>
          </p>

          <p class="mb-3 text-sm">
            <strong>Genre:</strong>
            <%= profile.genre %>
          </p>

          <p class="mb-3 text-sm">
            <strong>Telephone:</strong>
            <%= profile.telephone %>
          </p>

          <p class="mb-3 text-sm">
            <strong>Date birth:</strong>
            <%= profile.date_birth %>
          </p>

          <p class="mb-3 text-sm">
            <strong>Email:</strong>
            <%= profile.user.email %>
          </p>
          <br>
          <% if profile.user == current_user %>
          <p>
            <%= link_to "Profile settings", edit_profile_path(profile), class: "text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-green-300 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mb-2" %> |
            <%= link_to "Account settings", edit_user_registration_path, class: "text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-teal-300 dark:focus:ring-teal-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mb-2" %>
          </p>
          <% end %>
        </div>
        <br>
      </div>
    </div>
  </div>
  <br>

  <div class="flex flex-col mr-20 ml-20">
        <div>
            <h4 class="font-medium text-cyan-900 text-3xl text-center">Posts</h4><br>
            <div class="flex flex-col">
                <%= render @user_posts %>
            </div>
        </div>
    </div>
    

</div>

app/views/profiles/edit.html.erb
<h1 class="mt-20 mb-10 font-bold text-cyan-900 text-4xl text-center">Edit profile.</h1>
<div class="pr-96 pl-96 pb-20">
  <%= render "form", profile: @profile %>
  <div class="text-center mt-10">
    <%= link_to "Back", @profile, class: "text-white hover:text-cyan-900 bg-cyan-700 hover:bg-cyan-100 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  </div>
</div>

app/views/profiles/new.html.erb
<h2 class="mt-20 mb-10 font-bold text-cyan-900 text-4xl text-center">Create profile.</h2>
<div class="pr-96 pl-96 pb-20">
    <%= render "form", profile: @profile %>
</div>

app/views/profiles/show.html.erb
<%= render @profile %>