config/routes.rb
Rails.application.routes.draw do

  # Comments routes.
  get 'uncomment', to: 'comments#destroy'
  
  # Likes routes.
  get 'like', to: "likes#create"
  get 'dislike', to: "likes#destroy"

  # Connections routes.
  resources :connections
  get 'add/friend', to: "connections#create"
  get 'remove/friend', to: "connections#destroy"

  # Search routes.
  get 'result', to: 'searches#result'
  get 'search', to: 'searches#search_user'

  # Post routes.
  resources :posts do
    resources :comments, except: [:index]
  end

  # Profile routes.
  resources :profiles, except: [:index, :destroy]

  # Devise users routes.
  devise_for :users

  # Pages controller. 
  root 'pages#home'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true

  def self.look_up_comment(comment_id)
    where(id: comment_id).first.destroy
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :require_user
    before_action :user_doesnt_have_profile
    before_action :set_post_to_comment, only: [:create]

    def create
        @comment = @post.comments.create(comment_params)
        @comment.user_id = current_user.id
        #@message = @comment.valid?
        if @comment.save
            redirect_to post_path(@post)#, notice: "#{@message}, Comment: #{@comment.body}, Post: #{@comment.post_id}, User: #{@comment.user_id}"
        end
    end

    def destroy
        @comment = params[:comment]
        @post = params[:post]
        Comment.look_up_comment(@comment)
        redirect_to post_path(@post)
    end

    private
        def comment_params
            params.require(:comment).permit(:body)
        end

        def set_post_to_comment
            @post = Post.find(params[:post_id])
        end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="flex flex-row p-2">
    <div class="mt-auto mb-auto ml-0 mr-5">
        <%= image_tag(comment.user.profile.avatar, width: 30, class:"rounded-full  m-auto") if comment.user.profile.avatar.attached? %>
        <% if !comment.user.profile.avatar.attached? %>
            <img src="<%= asset_path( 'image-blank.png' ) %>" width= "30px" class="rounded-full  m-auto" />
        <% end %>
    </div>
    <div class="text-sm">
        <%= link_to "#{comment.user.profile.first_name} #{comment.user.profile.last_name}", profile_path(comment.user.profile), target: :_blank, class:"font-bold" %><br>
        <%= comment.body %><br>
        <% if request.path == post_path(comment.post) %>
            <% if current_user == comment.user %>
                <%= link_to 'Delete comment.', uncomment_path(comment: comment.id, post: comment.post), class:"text-red-600 text-xs" %><br>
            <% end %>
        <% end %>
        <span class="text-xs"><b>Created:</b> <%= time_ago_in_words(comment.created_at) %>.</span>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |form| %>
    <div class="flex flex-row">
        <%= form.text_field :body, class:"form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
        <%= form.submit  class:"text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-green-300 dark:focus:ring-green-800 text-m text-center p-2 rounded" %>
    </div>
<% end %>