config/routes.rb
Rails.application.routes.draw do

  # Comments routes.
  get 'uncomment', to: 'comments#destroy'
  
  # Likes routes.
  get 'like', to: "likes#create"
  get 'dislike', to: "likes#destroy"

  # Connections routes.
  resources :connections
  get 'add/friend', to: "connections#create"
  get 'remove/friend', to: "connections#destroy"

  # Search routes.
  get 'result', to: 'searches#result'
  get 'search', to: 'searches#search_user'

  # Post routes.
  resources :posts do
    resources :comments, except: [:index]
  end

  # Profile routes.
  resources :profiles, except: [:index, :destroy]

  # Devise users routes.
  devise_for :users

  # Pages controller. 
  root 'pages#home'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { minimum: 5 }
  has_rich_text :body
  has_many_attached :images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  #after_create_commit {broadcast_prepend_to "posts"}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_user
  before_action :user_doesnt_have_profile

  def show
    @post_comments = @post.comments.order('created_at DESC')
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post created successfully" }
      else
        #format.turbo_stream { render turbo_stream: turbo_stream.replace(@post, partial: "posts/form", locals: { post: @post })}
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, id: dom_id(@post)) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div>
    <%= form.rich_text_area :body %>
  </div>
  <br>
  <div class="mb-3 w-full">
    <%= form.label 'Images', class:"block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= form.file_field :images, multiple: true, class:"block w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 cursor-pointer dark:text-gray-400 focus:outline-none focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
  </div>

  <div>
    <%= form.submit class:"text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-green-300 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%#= turbo_frame_tag dom_id(post) do %>
    <div class="bg-cyan-50 mt-5 mb-5 p-5 rounded-lg shadow-lg flex flex-col">
        <div class="flex flex-row p-2">
            <div class="mr-5">
                <%= image_tag(post.user.profile.avatar, width: 50, class:"rounded-full  m-auto") if post.user.profile.avatar.attached? %>
                <% if !post.user.profile.avatar.attached? %>
                    <img src="<%= asset_path( 'image-blank.png' ) %>" width= "50px" class="rounded-full  m-auto" />
                <% end %>
            </div>
            <p>
                <%= link_to "#{post.user.profile.first_name} #{post.user.profile.last_name}", profile_path(post.user.profile), target: :_blank, class:"font-bold" %><br>
                <span class="text-xs font-bold"><%= post.user.profile.occupation %></span>
            </p>
            <div class="w-auto ml-auto mr-0 flex flex-row">
            <% if current_user == post.user %>
                <%= link_to "Edit post", edit_post_path(post), class:"text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
                <%= button_to "Delete post", post, method: :delete, form: { data: { turbo_confirm: "Are you sure?" }}, class:"text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
            <% end %>
            <% if !(request.path == post_path(post)) %>
                <%= link_to "Show post", post, class:"text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:ring-lime-300 dark:focus:ring-lime-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
            <% end %>
            </div>
        </div>
        <div>
            <div class="flex flex-row">
                <p class="text-sm mt-1 mb-1 ml-0 mr-auto">
                    <b>Created:</b> <%= time_ago_in_words(post.created_at) %>.
                </p>
                <p class="text-sm mt-1 mb-1 mr-0 ml-auto">
                <i class="far fa-comment"></i> <%= post.comments.count %>
                <% if !(Like.look_up_like(current_user.id, post.id).present?) %>
                    <%= link_to "", like_path(user: current_user.id, post: post.id), class:"far fa-thumbs-up" %> <%= post.likes.count %>
                <% else %>
                    <%= link_to "", dislike_path(user: current_user.id, post: post.id), class:"fas fa-thumbs-up" %> <%= post.likes.count %>
                <% end %>
                </p>
            </div>
            <p class="text-sm font-bold">
                <%= post.body %>
            </p>
            <% if post.images.attached? %>
              <div class="flex flex-row justify-center mt-5 mb-5">
              <% for i in 0...post.images.length %>
                <%= image_tag(post.images[i], width: 200, class: "ml-10 mr-10") %>
              <% end %>
              </div>
            <% end %>
        </div>
        <br>
        <div>
            <h3 class="text-1xl font-bold mb-2">Comments.</h3>
            <div>
                <%= render post.comments %>
            </div>
        </div>
        <% if request.path == post_path(post) %>
        <br>
            <div>
                <h3 class="text-1xl font-bold mb-2">Add comment.</h3>
            </div>
            <div>
                <div>
                    <%= render 'comments/form' %>
                </div>
            </div>
        <% end %>
    </div>
<%# end %>

app/views/posts/edit.html.erb
<div class="mt-10 pr-32 pl-32">
    <div class="bg-gray-50 mt-5 mb-5 p-5 rounded-lg shadow-lg">
        <%= render "form", post: @post %><br>
        <%= link_to "Cancel", @post, class:"text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="mt-10 pr-32 pl-32">
    <div>
        <%= render @post %>
    </div>
</div>